# Generated by Django 4.0 on 2021-12-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='', verbose_name='date of run detection')),
                ('count_pothole', models.IntegerField(default=0, verbose_name='count of pothole detection')),
                ('count_image', models.IntegerField(default=0, verbose_name='count of image save')),
                ('send_mail_state', models.BooleanField(default=False, verbose_name='status sending to mail')),
                ('url', models.CharField(default='', max_length=300, verbose_name='url of date_table')),
                ('slug', models.CharField(default='', max_length=100, verbose_name='date to slug')),
                ('send_detect', models.BooleanField(default=True, verbose_name='value of sending for processing')),
                ('error_processing', models.BooleanField(default=False, verbose_name='error or not to processing')),
            ],
            options={
                'verbose_name': 'Таблица с данными о каждом выезде',
                'verbose_name_plural': 'Таблица с данными о каждом выезде',
            },
        ),
        migrations.CreateModel(
            name='MailNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of mail')),
                ('description', models.CharField(max_length=100, verbose_name='description of mail')),
            ],
            options={
                'verbose_name': 'Таблица со списком адресов для отправки данных',
                'verbose_name_plural': 'Таблица со списком адресов для отправки данных',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='text of notification')),
            ],
            options={
                'verbose_name': 'Таблица, где храняться увидомления',
                'verbose_name_plural': 'Таблица, где храняться увидомления',
            },
        ),
        migrations.CreateModel(
            name='TrackerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('navigationtime', models.DateTimeField()),
                ('imei', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Таблица с данными полученные от ГЛОНАСС трекера',
                'verbose_name_plural': 'Таблица с данными полученные от ГЛОНАСС трекера',
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.FileField(upload_to='')),
                ('date_value', models.CharField(max_length=20, verbose_name='date of start video')),
                ('date_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.date_table')),
            ],
            options={
                'verbose_name': 'Таблица с данными полученные о загруженных файлах',
                'verbose_name_plural': 'Таблица с данными полученные о загруженных файлах',
            },
        ),
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True, verbose_name='url of image')),
                ('latitude', models.FloatField(verbose_name='latitude location of pothole')),
                ('longitude', models.FloatField(verbose_name='longitude location of pothole')),
                ('count_img_pothole', models.IntegerField(default=0, verbose_name='count of pothole detection in image')),
                ('date_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.date_table')),
            ],
            options={
                'verbose_name': 'Таблица с данными о каждой найденной яме',
                'verbose_name_plural': 'Таблица с данными о каждой найденной яме',
            },
        ),
        migrations.CreateModel(
            name='DetectedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_file', models.FileField(default='', upload_to='')),
                ('end_file', models.FileField(default='', upload_to='')),
                ('date_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.date_table')),
            ],
            options={
                'verbose_name': 'Таблица с обработанным файлом',
                'verbose_name_plural': 'Таблица с обработанным файлом',
            },
        ),
    ]
