# Generated by Django 4.0 on 2021-12-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date_table',
            new_name='DateTable',
        ),
    ]
