# Generated by Django 4.0 on 2021-12-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_date_table_datetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.FileField(upload_to='')),
                ('date_value', models.CharField(max_length=20, verbose_name='date of start video')),
                ('date_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaddate', to='base.datetable')),
            ],
            options={
                'verbose_name': 'Таблица с данными полученные о загруженных файлах',
                'verbose_name_plural': 'Таблица с данными полученные о загруженных файлах',
            },
        ),
        migrations.AlterField(
            model_name='pothole',
            name='date_table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pothols', to='base.datetable'),
        ),
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
