# Generated by Django 4.0.1 on 2022-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uploaddate_alter_pothole_date_table_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetable',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
