# Generated by Django 4.0.1 on 2022-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_datetable_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetable',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='url of date_table'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
