# Generated by Django 4.0.1 on 2022-01-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_url_pothole_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pothole',
            old_name='img',
            new_name='url',
        ),
    ]
