# Generated by Django 4.0.1 on 2022-01-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_img_pothole_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddate',
            name='date_table_id',
        ),
        migrations.AlterField(
            model_name='uploaddate',
            name='video_name',
            field=models.FileField(upload_to='upload_files/'),
        ),
    ]
