# Generated by Django 4.0.1 on 2022-01-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_uploaddate_date_table_id_alter_uploaddate_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddate',
            name='date_table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaddate', to='base.datetable'),
        ),
    ]
