# Generated by Django 4.0.1 on 2022-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_uploaddate_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddate',
            name='video_name',
            field=models.FileField(upload_to='upload_files'),
        ),
    ]
