# Generated by Django 4.0.1 on 2022-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_uploaddate_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='url_txt_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
