# Generated by Django 4.0.1 on 2022-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_pothole_url_txt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='url_txt_file',
            field=models.FileField(upload_to=''),
        ),
    ]
