# Generated by Django 4.0.1 on 2022-01-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_pothole_url_txt_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedfile',
            old_name='end_file',
            new_name='file_path',
        ),
        migrations.RemoveField(
            model_name='detectedfile',
            name='start_file',
        ),
    ]
